---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-0173
    - profile-0173
    - user-0173
    - webserver-0173

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"